id: P000724
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-16 16:39:08.740951
source_metadata:
  id: bdr:W3CN7829
  title: གསུང་འབུམ། པཎ་ཆེན་བསོད་ནམས་གྲགས་པ།
  author: ''
  volumes:
    c28b8cf02e7047088aeeff82e87eb440:
      image_group_id: I3CN7831
      title: ''
      volume_number: 1
      total_pages: 566
      base_file: v001.txt
    7eee5a4839774d3d9187f9395eae7ded:
      image_group_id: I3CN7832
      title: ''
      volume_number: 2
      total_pages: 238
      base_file: v002.txt
    30c81d669ea94b9e927512c347ddab8c:
      image_group_id: I3CN7833
      title: ''
      volume_number: 3
      total_pages: 358
      base_file: v003.txt
    da17f354660a4eed9bef77a0eb0ca8f8:
      image_group_id: I3CN7834
      title: ''
      volume_number: 4
      total_pages: 438
      base_file: v004.txt
    a416be7c25b64f81acf83ea8e185a17d:
      image_group_id: I3CN7835
      title: ''
      volume_number: 5
      total_pages: 416
      base_file: v005.txt
    951e0c8f57904c3dbed282eb191d705d:
      image_group_id: I3CN7836
      title: ''
      volume_number: 6
      total_pages: 404
      base_file: v006.txt
    fbd65b112155443786cd38fd180099c8:
      image_group_id: I3CN7837
      title: ''
      volume_number: 7
      total_pages: 368
      base_file: v007.txt
    aa1c07ac63f84574b2e58d1796967c02:
      image_group_id: I3CN7838
      title: ''
      volume_number: 8
      total_pages: 0
    17594b4d9af647d88b3984b089b0575c:
      image_group_id: I3CN7839
      title: ''
      volume_number: 9
      total_pages: 382
      base_file: v008.txt
    1f7f3c551eaf481892ee4aebca28623f:
      image_group_id: I3CN7840
      title: ''
      volume_number: 10
      total_pages: 390
      base_file: v009.txt
    9d5e4c49eb8344f29b655f24cf77a211:
      image_group_id: I3CN7841
      title: ''
      volume_number: 11
      total_pages: 372
      base_file: v010.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
