id: I7B3AD38F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T02:23:49+00:00'
last_modified: '2022-06-10T10:11:00.936972+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7829
  title: གསུང་འབུམ། པཎ་ཆེན་བསོད་ནམས་གྲགས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    BE23:
      image_group_id: I3CN7831
      title: ''
      total_pages: 566
      order: 1
      base_file: BE23.txt
    66FA:
      image_group_id: I3CN7832
      title: ''
      total_pages: 238
      order: 2
      base_file: 66FA.txt
    B52C:
      image_group_id: I3CN7833
      title: ''
      total_pages: 358
      order: 3
      base_file: B52C.txt
    B433:
      image_group_id: I3CN7834
      title: ''
      total_pages: 438
      order: 4
      base_file: B433.txt
    '6823':
      image_group_id: I3CN7835
      title: ''
      total_pages: 416
      order: 5
      base_file: 6823.txt
    EB44:
      image_group_id: I3CN7836
      title: ''
      total_pages: 404
      order: 6
      base_file: EB44.txt
    71FF:
      image_group_id: I3CN7837
      title: ''
      total_pages: 368
      order: 7
      base_file: 71FF.txt
    FC4E:
      image_group_id: I3CN7838
      title: ''
      total_pages: 0
      order: 8
      base_file: FC4E.txt
    D71D:
      image_group_id: I3CN7839
      title: ''
      total_pages: 382
      order: 9
      base_file: D71D.txt
    C881:
      image_group_id: I3CN7840
      title: ''
      total_pages: 390
      order: 10
      base_file: C881.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
